const inventoryItem = [
    {
        itemNo: 1,
        itemName: 'Vegetables & Fruits',
        availability: true,
        collapsed: true,
        subItems: [
            {
                itemNo: 11,
                itemName: 'Vegetables',
                availability: true,
                collapsed: false,
                subItems: [
                    {
                        itemNo: 111,
                        itemName: 'Cucumber',
                        color: '#00B121',
                        option: 'Small',
                        sku_id: 'SKU02596051',
                        stock: '10',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 112,
                        itemName: 'Green Chilli',
                        color: '#00B122',
                        option: 'Medium',
                        sku_id: 'SKU02596052',
                        stock: '23',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 113,
                        itemName: 'Carrot',
                        color: '#00B123',
                        option: 'Large',
                        sku_id: 'SKU02596053',
                        stock: '34',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 114,
                        itemName: 'Pottato',
                        color: '#00B124',
                        option: 'Medium',
                        sku_id: 'SKU02596054',
                        stock: '50',
                        unlimited: false,
                        edit: false,
                    }
                ],
            },
            {
                itemNo: 12,
                itemName: 'Fruits',
                availability: true,
                collapsed: false,
                subItems: [
                    {
                        itemNo: 121,
                        itemName: 'Pineapple',
                        color: '#00B125',
                        option: 'Large',
                        sku_id: 'SKU02596055',
                        stock: '100',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 122,
                        itemName: 'Banana',
                        color: '#00B126',
                        option: 'Small',
                        sku_id: 'SKU02596056',
                        stock: '250',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 123,
                        itemName: 'Green Apple',
                        color: '#00B127',
                        option: 'Large',
                        sku_id: 'SKU02596057',
                        stock: '130',
                        unlimited: false,
                        edit: false,
                    },
                ],
            }
        ],
    },
    {
        itemNo: 2,
        itemName: 'Breads & Dairy',
        availability: true,
        collapsed: false,
        subItems: [
            {
                itemNo: 21,
                itemName: 'Breads',
                availability: true,
                collapsed: false,
                subItems: [
                    {
                        itemNo: 211,
                        itemName: 'Wheat Bread',
                        color: '#00B128',
                        option: 'Small',
                        sku_id: 'SKU02596058',
                        stock: '10',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 212,
                        itemName: 'Brown Bread',
                        color: '#00B129',
                        option: 'Medium',
                        sku_id: 'SKU02596059',
                        stock: '23',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 213,
                        itemName: 'Banana Bread',
                        color: '#00B130',
                        option: 'Large',
                        sku_id: 'SKU02596061',
                        stock: '34',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 214,
                        itemName: 'Multigrain Bread',
                        color: '#00B131',
                        option: 'Medium',
                        sku_id: 'SKU02596062',
                        stock: '50',
                        unlimited: false,
                        edit: false,
                    }
                ],
            },
            {
                itemNo: 22,
                itemName: 'Dairy',
                availability: true,
                collapsed: false,
                subItems: [
                    {
                        itemNo: 221,
                        itemName: 'Milk',
                        color: '#00B132',
                        option: 'Small',
                        sku_id: 'SKU02596063',
                        stock: '2',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 222,
                        itemName: 'Curd',
                        color: '#00B133',
                        option: 'Small',
                        sku_id: 'SKU02596064',
                        stock: '5',
                        unlimited: false,
                        edit: false,
                    },
                    {
                        itemNo: 223,
                        itemName: 'Ghee',
                        color: '#00B134',
                        option: 'Small',
                        sku_id: 'SKU02596065',
                        stock: '1',
                        unlimited: false,
                        edit: false,
                    },
                ],
            },
        ],
    },
    {
        itemNo: 3,
        itemName: 'Snacks',
        availability: true,
        collapsed: false,
        subItems: [
            {
                itemNo: 31,
                itemName: 'Chips',
                color: '#00B135',
                option: 'Small',
                sku_id: 'SKU02596066',
                stock: '10',
                unlimited: false,
                edit: false,
            },
            {
                itemNo: 32,
                itemName: 'Biscuit',
                color: '#00B136',
                option: 'Medium',
                sku_id: 'SKU02596067',
                stock: '23',
                unlimited: false,
                edit: false,
            },
        ],
    },
    {
        itemNo: 4,
        itemName: 'Cleaning and Household',
        availability: true,
        collapsed: false,
        subItems: [
            {
                itemNo: 41,
                itemName: 'Bleaching powder',
                color: '#00B137',
                option: 'Large',
                sku_id: 'SKU02596068',
                stock: '3',
                unlimited: false,
                edit: false,
            }
        ],
    },
];
export default inventoryItem;